SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Book.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment
{
    [Authorize(Roles = "User")]
    public class BookModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private readonly BookingService _bookingService;
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;
        private IWebHostEnvironment _environment;

        public BookModel(UserManager<ApplicationUser> userManager, BookingService bookingService, SlotService slotService, SlotSessionService slotSessionService, IWebHostEnvironment environment)
        {
            this.userManager = userManager;
            _bookingService = bookingService;
            _slotService = slotService;
            _slotSessionService = slotSessionService;
            _environment = environment;
        }

        [BindProperty]
        public Booking MyBooking { get; set; } = new();

        [BindProperty]
        public Slot MySlot { get; set; } = new();

        public List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();
        public DateTime? DateSelected { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetDateSelector(DateTime selectedDate)
        {
            SlotList.Clear();
            SlotSessionList.Clear();

            DateSelected = selectedDate;
            if (selectedDate < DateTime.Now.Date)
            {
                TempData["FlashMessage.Type"] = "warning";
                TempData["FlashMessage.Text"] = string.Format("Please select a valid date.");
                return Page();
            }
            List<Slot> rawSlot = _slotService.GetAll();
            SlotSessionList = _slotSessionService.GetAll();

            foreach (var slot in rawSlot)
            {
                if (slot.SlotDate == selectedDate)
                {
                    if (slot.SlotAvailability)
                    {
                        if (selectedDate.ToShortDateString() == DateTime.Now.ToShortDateString())
                        {
                            if (slot.SlotSession.SlotTime.TimeOfDay > DateTime.Now.TimeOfDay)
                            {
                                SlotList.Add(slot);
                            }
                        }
                        else
                        {
                            SlotList.Add(slot);
                        }
                    }
                }
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var userId = userManager.GetUserId(HttpContext.User);
            if (userId != null)
            {
                ApplicationUser user = userManager.FindByIdAsync(userId).Result;
                MyBooking.ApplicationUserId = user.Id;

                Slot? slot = _slotService.GetSlotById(MySlot.SlotId);
                if (slot == null)
                {
                    TempData["FlashMessage.Type"] = "danger";
                    TempData["FlashMessage.Text"] = string.Format("An error occurred while processing your booking. Please try again.");
                    return Page();
                }

                if (!slot.SlotAvailability)
                {
                    TempData["FlashMessage.Type"] = "danger";
                    TempData["FlashMessage.Text"] = string.Format("Our apologies, but the appointment slot you selected is no longer available as another user has booked it. Please click 'Refresh Slots Availability' to get the latest available slots.");
                    return Page();
                }

                slot.SlotAvailability = false;
                _slotService.UpdateSlot(slot);

                MyBooking.BookingStatus = "Confirmed";
                MyBooking.SlotId = MySlot.SlotId;
                _bookingService.AddBooking(MyBooking);

                TempData["FlashMessage.Type"] = "success";
                TempData["FlashMessage.Text"] = string.Format("You've successfully booked an appointment (ID: {0}). Please arrive at least five minutes before your time slot.", MyBooking.BookingId);

            }
            return RedirectToPage("/Appointment/Index");
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment
{
    [Authorize(Roles = "User")]
    public class DetailsModel : PageModel
    {
        private readonly BookingService _bookingService;
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;

        public DetailsModel(BookingService bookingService, SlotService slotService, SlotSessionService slotSessionService)
        {
            _bookingService = bookingService;
            _slotService = slotService;
            _slotSessionService = slotSessionService;
        }

        [BindProperty]
        public Booking MyBooking { get; set; } = new();

        public Slot Slot { get; set; } = new();

        public static List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();

        public IActionResult OnGet(int id)
        {
            SlotList = _slotService.GetAll();
            SlotSessionList = _slotSessionService.GetAll();

            Booking? booking = _bookingService.GetBookingById(id);
            if (booking != null)
            {
                MyBooking = booking;
                return Page();
            }
            else
            {
                TempData["FlashMessage.Type"] = "danger";
                TempData["FlashMessage.Text"] = string.Format("Booking ID {0} is not found.", id);
                return RedirectToPage("/Appointment/Index");
            }
        }
        
        public async Task<IActionResult> OnPostAsync(int id)
        {
            _bookingService.RemoveBooking(id);

            TempData["FlashMessage.Type"] = "success";
            TempData["FlashMessage.Text"] = string.Format("You have successfully cancelled your appointment.");
            return RedirectToPage("/Appointment/Index");
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment
{
    [Authorize(Roles = "User")]
    public class IndexModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private readonly BookingService _bookingService;
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;

        public IndexModel(UserManager<ApplicationUser> userManager, BookingService bookingService, SlotService slotService, SlotSessionService slotSessionService)
        {
            this.userManager = userManager;
            _bookingService = bookingService;
            _slotService = slotService;
            _slotSessionService = slotSessionService;
        }

        public List<Booking> BookingList { get; set; } = new();

        public static List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();

        public void OnGet()
        {
            List<Booking> AllBookingList = _bookingService.GetAll();
            SlotList = _slotService.GetAll();
            SlotSessionList = _slotSessionService.GetAll();

            var userId = userManager.GetUserId(HttpContext.User);
            if (userId != null)
            {
                foreach (var booking in AllBookingList)
                {
                    if (booking.ApplicationUserId == userId)
                    {
                        BookingList.Add(booking);
                    }
                }
            }
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Staff/Add.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment.Staff
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;
        private IWebHostEnvironment _environment;

        public AddModel(SlotService slotService, SlotSessionService slotSessionService, IWebHostEnvironment environment)
        {
            _slotService = slotService;
            _slotSessionService = slotSessionService;
            _environment = environment;
        }

        [BindProperty]
        public Slot MySlot { get; set; } = new();
        public List<SlotSession> SlotSessionList { get; set; } = new();

        public DateTime? DateSelected { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetDateSelector(DateTime date)
        {
            SlotSessionList.Clear();

            DateSelected = date;
            if (date < DateTime.Now.Date)
            {
                TempData["FlashMessage.Type"] = "warning";
                TempData["FlashMessage.Text"] = string.Format("Please select a valid date.");
                return Page();
            }

            List<Slot> dbSlots = _slotService.GetAll();
            List<SlotSession> dbSlotSessions = _slotSessionService.GetAll();

            if (dbSlots.Count != 0)
            {
                foreach (var slot in dbSlots)
                {
                    foreach (var session in dbSlotSessions)
                    {
                        if (slot.SlotDate.Date != date.Date)
                        {
                            SlotSessionList.Add(session);
                        }
                        else
                        {
                            if (slot.SlotSession.SlotTime.TimeOfDay > DateTime.Now.TimeOfDay)
                            {
                                SlotSessionList.Add(session);
                            }
                        }
                    }
                }
            }
            else
            {
                if (date.Date == DateTime.Now.Date)
                {
                    foreach (var session in dbSlotSessions)
                    {
                        if (session.SlotTime.TimeOfDay > DateTime.Now.TimeOfDay)
                        {
                            SlotSessionList.Add(session);
                        }
                    }
                }
                else
                {
                    foreach (var session in dbSlotSessions)
                    {
                        SlotSessionList.Add(session);
                    }
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                MySlot.SlotAvailability = true;
                _slotService.AddSlot(MySlot);
                TempData["FlashMessage.Type"] = "success";
                TempData["FlashMessage.Text"] = string.Format("You've successfully added an appointment slot for {0}.", MySlot.SlotDate.ToShortDateString());
            }
            else
            {
                TempData["FlashMessage.Type"] = "danger";
                TempData["FlashMessage.Text"] = string.Format("Error encountered while adding slot. Please try again!");
            }
            return Page();
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Staff/BookingInfo.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment.Staff
{
    [Authorize(Roles = "Admin")]
    public class BookingInfoModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private readonly BookingService _bookingService;
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;

        public BookingInfoModel(UserManager<ApplicationUser> userManager, BookingService bookingService, SlotService slotService, SlotSessionService slotSessionService)
        {
            this.userManager = userManager;
            _bookingService = bookingService;
            _slotService = slotService;
            _slotSessionService = slotSessionService;
        }

        [BindProperty]
        public Booking MyBooking { get; set; } = new();

        public Slot Slot { get; set; } = new();

        public static List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();

        public IActionResult OnGet(int id)
        {
            SlotList = _slotService.GetAll();
            SlotSessionList = _slotSessionService.GetAll();

            Booking? booking = _bookingService.GetBookingById(id);
            if (booking != null)
            {
                MyBooking = booking;
                return Page();
            }
            else
            {
                TempData["FlashMessage.Type"] = "danger";
                TempData["FlashMessage.Text"] = string.Format("Booking ID {0} is not found.", id);
                return RedirectToPage("/Appointment/Index");
            }
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            MyBooking.BookingStatus = "Completed";
            _bookingService.UpdateBooking(MyBooking);

            TempData["FlashMessage.Type"] = "success";
            TempData["FlashMessage.Text"] = string.Format("You have successfully cancelled your appointment.");
            return RedirectToPage("/Appointment/Index");
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Staff/BookingList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment.Staff
{
    [Authorize(Roles = "Admin")]
    public class BookingListModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private readonly BookingService _bookingService;
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;

        public BookingListModel(UserManager<ApplicationUser> userManager, BookingService bookingService, SlotService slotService, SlotSessionService slotSessionService)
        {
            this.userManager = userManager;
            _bookingService = bookingService;
            _slotService = slotService;
            _slotSessionService = slotSessionService;
        }

        public List<Booking> BookingList { get; set; } = new();

        public static List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();

        public void OnGet()
        {
            BookingList = _bookingService.GetAll();
            SlotList = _slotService.GetAll();
            SlotSessionList = _slotSessionService.GetAll();
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Staff/Console.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Appointment.Staff
{
    [Authorize(Roles = "Admin")]
    public class ConsoleModel : PageModel
    {
        private readonly SlotService _slotService;
        private readonly SlotSessionService _slotSessionService;
        private IWebHostEnvironment _environment;

        public ConsoleModel(SlotService slotService, SlotSessionService slotSessionService, IWebHostEnvironment environment)
        {
            _slotService = slotService;
            _slotSessionService = slotSessionService;
            _environment = environment;
        }

        public List<Slot> SlotList { get; set; } = new();
        public static List<SlotSession> SlotSessionList { get; set; } = new();

        public DateTime? DateSelected { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnGetDateSelector(DateTime date)
        {
            SlotList.Clear();
            SlotSessionList.Clear();

            SlotSessionList = _slotSessionService.GetAll();

            DateSelected = date;

            List<Slot> dbSlots = _slotService.GetAll();

            if (dbSlots.Count > 0)
            {
                foreach (var slot in dbSlots)
                {
                    if (slot.SlotDate.Date == date.Date)
                    {
                        SlotList.Add(slot);
                    }
                }
            }
            return Page();
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Book.cshtml
@page
@model SusFoodBank.Pages.Appointment.BookModel
@{
    ViewData["Title"] = "Book Visitation Appointment";
}

<div class="container my-4">
    <div class="card py-3 mx-auto" style="max-width: 800px;">
        <div class="card-body">
            <h3 class="fw-bold text-center mb-3">Book Visitation Appointment</h3>
            <div class="alert alert-info mb-0" role="alert">
                <p class="fw-bold mb-1">
                    <i class="fa-regular fa-circle-question me-1"></i>Please read before booking a visitation appointment:
                </p>
                <ul class="mb-0">
                    <li>Booking a visitation appointment gives you priority to be served over walk-in donors when you arrive at our food bank.</li>
                    <li>Please ensure you can show up for the selected date and time slot, as late-comers will not have queue priority and need to join the existing queue.</li>
                </ul>
            </div>

            <hr />
            @await Html.PartialAsync("_FlashMessage")
            <a asp-page="/Appointment/Book" class="btn btn-secondary mb-3">Refresh Slots Availability</a>

            <div class="mb-1">
                <small>
                    <span class="fw-bold">Note:</span> Date and time slots displayed are in UTC+8 &lpar;Singapore time&rpar;.
                </small>
            </div>
            <div class="mb-3">
                <h5 class="fw-bold">
                    <i class="fa-regular fa-calendar me-1"></i>Appointment Date
                </h5>
                <div class="mb-4">
                    <p class="mb-1">Please select an appointment date:</p>
                    <form method="get" asp-page-handler="DateSelector">
                        <input type="hidden" name="handler" value="DateSelector" />
                        <input type="date" class="form-control" asp-for="DateSelected" name="SelectedDate" style="max-width: 350px;" onchange="this.form.submit()" />
                        <span class="text-danger"></span>
                    </form>
                </div>
            </div>

            <div>
                <h5 class="fw-bold">
                    <i class="fa-regular fa-clock me-1"></i>Appointment Time Slot
                </h5>
                @{
                    if (Model.SlotList.Count == 0)
                    {
                        <p class="fst-italic">No time slot available.</p>
                    }
                    else
                    {
                        <p class="mb-1">Please select an appointment time slot:</p>
                        <form method="post">
                            <div class="mb-2">
                                <small class="fw-bold fst-italic">Morning slots:</small>
                                <div class="radio-dts-selector">
                                    @{
                                        foreach (var slot in Model.SlotList.Distinct())
                                        {
                                            if (slot.SlotSession.SlotSessionId <= 6)
                                            {
                                                <input type="radio" asp-for="MySlot.SlotId" id="@slot.SlotId" value="@slot.SlotId">
                                                <label for="@slot.SlotId">@slot.SlotSession.SlotTime.ToShortTimeString()</label>
                                            }
                                        }
                                    }
                                </div>
                            </div>
                            <div class="mb-4">
                                <small class="fw-bold fst-italic">Afternoon slots:</small>
                                <div class="radio-dts-selector">
                                    @{
                                        foreach (var slot in Model.SlotList.Distinct())
                                        {
                                            if (slot.SlotSession.SlotSessionId >= 7)
                                            {
                                                <input type="radio" asp-for="MySlot.SlotId" id="@slot.SlotId" value="@slot.SlotId">
                                                <label for="@slot.SlotId">@slot.SlotSession.SlotTime.ToShortTimeString()</label>
                                            }
                                        }
                                    }
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary btn-lg">Submit Booking</button>
                        </form>
                    }
                }
            </div>
        </div>
    </div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Details.cshtml
@page
@model SusFoodBank.Pages.Appointment.DetailsModel
@{
    ViewData["Title"] = "Visitation Appointment Details";
}

<div class="container my-4">
    <div class="card py-3 mx-auto" style="max-width: 800px;">
        <div class="card-body">
            <h3 class="fw-bold text-center mb-3">Visitation Appointment Details</h3>
            <p>Dear Sir/Madam,</p>
            <p class="mb-0">Please find below the details of your visitation appointment:</p>
            <ul class="list-unstyled my-4">
                <li>
                    <span class="fw-bold"><i class="fa-regular fa-calendar me-1"></i>Appointment Date: </span>@Model.MyBooking.Slot.SlotDate.ToString("dd MMMM yyyy")
                </li>
                <li>
                    <span class="fw-bold"><i class="fa-regular fa-clock me-1"></i>Appointment Time Slot: </span>@Model.MyBooking.Slot.SlotSession.SlotTime.ToShortTimeString()
                </li>
                <li>
                    <span class="fw-bold"><i class="fa-solid fa-location-dot me-1"></i>Address: </span>
                    <br />
                    SusFoodBank
                    <br />
                    180 Ang Mo Kio Avenue 8
                    <br />
                    Singapore 569830
                </li>
            </ul>
            <div class="mb-3">
                <small class="fw-bold text-danger">Please be reminded to arrive at least five minutes before your appointment time slot. Latecomers will be issued a new queue ticket and asked to join the queue.</small>
            </div>
            <div class="mb-3">
                <p class="mb-0">Thank you.</p>
                <p class="fst-italic">~ SusFoodBank</p>
            </div>
            <div class="mb-2">
                <div class="d-grid gap-2 d-md-block">
                    @if (Model.MyBooking.BookingStatus != "Completed")
                    {
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelModal">Cancel Appointment</button>
                    }
                    <a asp-page="/Appointment/Index" class="btn btn-secondary">
                        <i class="fa-solid fa-clock-rotate-left me-1"></i>Back to History
                    </a>
                </div>
            </div>
            <small class="fst-italic">Booking ID: @Model.MyBooking.BookingId</small>
        </div>
    </div>
</div>

<div class="modal fade" id="cancelModal" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="cancelModalLabel">Confirmation</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Do you want to cancel this appointment?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link" data-bs-dismiss="modal">No, take me back!</button>
                <form method="post">
                    <button type="submit" class="btn btn-danger">Cancel Appointment</button>
                </form>
            </div>
        </div>
    </div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Appointment/Index.cshtml
@page
@model SusFoodBank.Pages.Appointment.IndexModel
@{
    ViewData["Title"] = "My Visitation Appointment History";
}

<div class="container my-4">
    <div class="card">
        <div class="card-body my-3">
            <h3 class="fw-bold text-center mb-3">Visitation Appointment Booking History</h3>

            <hr />

            @await Html.PartialAsync("_FlashMessage")
            @{
                if (Model.BookingList.Count == 0)
                {
                    <div class="text-center">
                        <p>You have not booked any visitation appointments as of now.</p>
                        <a asp-page="/Appointment/Book" class="btn btn-primary">Book Appointment</a>
                    </div>
                }
                else
                {
                    <div class="d-flex justify-content-start justify-content-lg-end">
                        <a asp-page="/Appointment/Book" class="btn btn-primary mb-3">Book Appointment</a>
                    </div>
                    <div class="table-responsive-xxl">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col" style="width: 85px;">Booking ID</th>
                                    <th scope="col" style="width: 135px;">Appointment Date</th>
                                    <th scope="col" style="width: 135px;">Appointment Time Slot</th>
                                    <th scope="col" style="width: 100px;">Status</th>
                                    <th scope="col" style="width: 170px">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var booking in Model.BookingList)
                                {
                                    <tr>
                                        <th scope="row">@booking.BookingId</th>
                                        <td>@booking.Slot.SlotDate.ToString("dd MMMM yyyy")</td>
                                        <td>@booking.Slot.SlotSession.SlotTime.ToShortTimeString()</td>
                                        <td>
                                            @if (@booking.BookingStatus == "Confirmed")
                                            {
                                                <span class="badge rounded-pill text-bg-success">confirmed</span>
                                            }
                                            else if (@booking.BookingStatus == "Completed")
                                            {
                                                <span class="badge rounded-pill text-bg-secondary">completed</span>
                                            }
                                        </td>

                                        <td>
                                            <a asp-page="/Appointment/Details" asp-route-id="@booking.BookingId" class="btn btn-secondary">View Details</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
            }
        </div>
    </div>
</div>