SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/AddLocation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Feedback
{
    [Authorize]
    [Authorize(Roles = "User")]
    public class AddLocationModel : PageModel
	{
		private readonly LocationService _locationService;

		public AddLocationModel(LocationService locationService)
		{
			_locationService = locationService;
		}

		[BindProperty]
		public Locations locations { get; set; } = new();


		public void OnGet()
		{
		}

		public IActionResult OnPost()
		{
			if (ModelState.IsValid)
			{
				_locationService.AddLocation(locations);
				TempData["FlashMessage.Type"] = "success";
				TempData["FlashMessage.Text"] = string.Format(" {0} is added", locations.Location);
				return Redirect("/Feedback/ViewLocations");
			}
			return Page();
		}
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/LocationDetails.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Feedback
{
    [Authorize]
    [Authorize(Roles = "User")]
    public class LocationDetailsModel : PageModel
	{

		private readonly LocationService _locationService;
		private readonly MyDbContext _DbContext;
		public LocationDetailsModel(LocationService locationService, MyDbContext context)
		{
			_locationService = locationService;
			_DbContext = context;
		}

		[BindProperty]
		public Locations locations { get; set; } = new();

		public List<Locations> LocationsList { get; set; } = new();

		public IActionResult OnGet(int id)
		{
			LocationsList = _locationService.GetAll();

			Locations? location = _locationService.GetLocationById(id);
			if (location != null)
			{
				locations = location;
				return Page();
			}
			else
			{
				TempData["FlashMessage.Type"] = "danger";
				TempData["FlashMessage.Text"] = string.Format("Location ID {0} not found", id);
				return Redirect("/Feedback/ViewLocations");
			}
		}

		public IActionResult OnPost()
		{
			if (ModelState.IsValid)
			{
				_locationService.UpdateLocation(locations);
				return Redirect("/Feedback/ViewLocations");
			}
			return Page();
		}

        public IActionResult OnPostDelete()
        {
            _locationService.RemoveLocation(locations);
            return Redirect("/Feedback/LocationDetails");
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/ViewLocations.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Org.BouncyCastle.Utilities;
using SusFoodBank.Models;
using SusFoodBank.Services;
using System.Data;

namespace SusFoodBank.Pages.Feedback
{
    [Authorize]
    [Authorize(Roles = "User")]
    public class ViewLocationsModel : PageModel
	{
		private readonly LocationService _locationService;

		public Locations Location { get; set; } = new();


		////Count how many
		//public int A()
		//{
		//    string stmt = "SELECT COUNT(*) FROM dbo.Locations";
		//    int count = 0;

		//    using (SqlConnection thisConnection = new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=SusFoodBankDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"))
		//    {
		//        using (SqlCommand cmdCount = new SqlCommand(stmt, thisConnection))
		//        {
		//            thisConnection.Open();
		//            count = (int)cmdCount.ExecuteScalar();
		//        }
		//    }
		//    return count;
		//}

		public List<Locations> LocationList { get; set; } = new();
		public ViewLocationsModel(LocationService locationService)
		{
			_locationService = locationService;
		}

		public void OnGet()
		{

			LocationList = _locationService.GetAll();
		}
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/AddLocation.cshtml
@page
@model SusFoodBank.Pages.Feedback.AddLocationModel
@{

    ViewData["Title"] = "Add location";

}

<br /><br />
<div class="text-center">
    <h1>Enter a location here for our consideration!</h1><br />

    <p>Or click here to view all existing suggestions

           <a class="btn btn-secondary ms-3" asp-page="/feedback/ViewLocations">View</a>
    </p>
</div>

<div class="container-sm" style="margin-top:25px">
    <div class="col-sm-6" style="margin-top:25px">
        <form class="mt-3" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>


            <div class="form-group">
                <label class="col-sm-2 col-form-label" asp-for="locations.Location"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="locations.Location" oninput="this.value = this.value()" placeholder="Enter location here" />
                    <span asp-validation-for="locations.Location" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 col-form-label" asp-for="locations.Reason"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="locations.Reason" oninput="this.value = this.value()" placeholder="Reason" />
                    <span asp-validation-for="locations.Reason" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div>
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/LocationDetails.cshtml
@page
@model SusFoodBank.Pages.Feedback.LocationDetailsModel
@{
}


<br />
<br />
<div class="text-center">
    <h1>Changed your mind? <br /> Update/delete your location(s) here</h1><br />
</div>

<div class="text-center">
    <h3>

        Click here to view all locations

        <a class="btn btn-secondary ms-3" asp-page="/feedback/ViewLocations">Back</a>

    </h3>
</div>

<div class="container-sm" style="margin-top:25px">
    <div class="col-sm-6" style="margin-top:25px">
        <form class="mt-3" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row mb-3" hidden>
                <label class="col-sm-2 col-form-label" asp-for="locations.Id" hidden></label>
                <div class="col-sm-10" hidden>
                    <input class="form-control" asp-for="locations.Id" hidden />
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 col-form-label" asp-for="locations.Location"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="locations.Location" oninput="this.value = this.value()" placeholder="Enter location here" />
                    <span asp-validation-for="locations.Location" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 col-form-label" asp-for="locations.Reason"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="locations.Reason" oninput="this.value = this.value()" placeholder="Reason" />
                    <span asp-validation-for="locations.Reason" class="text-danger"></span>
                </div>
            </div>
            <br />
            <br />
            <div>
                <input type="submit" class="btn btn-danger" asp-page-handler="Delete" value="Delete" id="Delete" />
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/Feedback/ViewLocations.cshtml
@page
@model SusFoodBank.Pages.Feedback.ViewLocationsModel
@{
    ViewData["Title"] = "Details";
}

<br />

<div class="col-sm-12" style="margin-top:25px">
    <div class="text-center">
        <h1>Thanks for the feedback!</h1><br />
        <p>
            Or click here to view add another location suggestion

            <a class="btn btn-secondary ms-3" asp-page="/feedback/AddLocation">Add</a>
        </p>
    </div>

    <div>
        <p></p>
    </div>

    <div class="container-sm" style="margin-top:25px">
        <table class="table mt-3">
            <thead>
                <tr>
                    <th hidden>@Html.DisplayNameFor(model => model.LocationList[0].Id)</th>
                    <th>@Html.DisplayNameFor(model => model.LocationList[0].Location)</th>
                    <th>@Html.DisplayNameFor(model => model.LocationList[0].Reason)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @{
                    @foreach (var item in Model.LocationList)
                    {
                        <tr>
                            <td hidden>@item.Id</td>
                            <td>@item.Location</td>
                            <td>@item.Reason</td>
                            <td>
                                <a class="btn btn-primary btn-sm" asp-page="/feedback/LocationDetails" asp-route-id="@item.Id">View</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>