SusFoodBank (ASP.NET Core)/SusFoodBank/Models/ChangePassword.cs
namespace SusFoodBank.Models
{
	public class ChangePassword
	{
		public string newpassword { get; set; }
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Models/Changepassworduser.cs
namespace SusFoodBank.Models
{
	public class Changepassworduser
	{

		public string oldpassword { get; set; }
		public string newpassword { get; set; }
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace SusFoodBank.Models
{
	public class Login
	{
		[Required]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; } = string.Empty;
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; } = string.Empty;
		public bool RememberMe { get; set; }
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/AccountDetails.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
    [Authorize]
    [Authorize(Roles = "User")]
    public class AccountDetailsModel : PageModel


    {
        public string datevalue { get; set; }
        public string datelist { get; set; }
        public string NoLogin { get; set; }
        private UserManager<ApplicationUser> userManager { get; }
        private MyDbContext MyDbContext;

        private SignInManager<ApplicationUser> signInManager { get; }

        public AccountDetailsModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, MyDbContext myDbContext)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.MyDbContext = myDbContext;
        }
        public void OnGet()
        {
            var user = userManager.FindByNameAsync(User.Identity.Name).Result;
            var list = MyDbContext.loginlist.ToList();
            var output = MyDbContext.loginlist.Where(i => i.ApplicationUser.Id == user.Id).GroupBy(l => l.Date, l => l, (key, g) => new { Key = key, Count = g.Count() });
            var date1 = new List<string>();
            var date2 = new List<int>();

            foreach (var item in output)
            {
                Console.WriteLine($"{item}");
                date1.Add(item.Key);
                date2.Add(item.Count);

            }
            datelist = System.Text.Json.JsonSerializer.Serialize(date1);
            datevalue = System.Text.Json.JsonSerializer.Serialize(date2);

            var analytics = MyDbContext.Analytics.Where(i => i.ApplicationUser.Id == user.Id).First();
            NoLogin = analytics.LoginCount.ToString();


        }
        public async Task<IActionResult> OnPostDeleteAccAsync()
        {
            var user = userManager.FindByNameAsync(User.Identity.Name).Result;
            user.Deleted = true;
            var result = await userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                await signInManager.SignOutAsync();
                return Redirect("/usermanagement/Login");
            }
            return Redirect("/");
        }


        //link update here as well 



    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/AdminRegister.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
	public class AdminRegisterModel : PageModel
	{
		private UserManager<ApplicationUser> userManager { get; }
		private SignInManager<ApplicationUser> signInManager { get; }

		private RoleManager<IdentityRole> roleManager;
		private MyDbContext MyDbContext;

		private IWebHostEnvironment _environment;

		[BindProperty]
		public Register RModel { get; set; } = new();
		[BindProperty]
		public IFormFile? Upload { get; set; }

		public string[] Genders { get; set; } = new[] { "Male", "Female", "Unspecified" };
		public AdminRegisterModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IWebHostEnvironment environment, RoleManager<IdentityRole> roleManager, MyDbContext myDbContext)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
			_environment = environment;
			this.roleManager = roleManager;
			MyDbContext = myDbContext;
		}
		public void OnGet()
		{
		}
		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var URL = "";
				if (Upload != null)
				{

					//if (Upload.Length > 2 * 1024 * 1024)
					//{
					//	ModelState.AddModelError("Upload",
					//	"File size cannot exceed 2MB.");
					//	return Page();
					//}
					var uploadsFolder = "uploads";
					var imageFile = Guid.NewGuid() + Path.GetExtension(
					Upload.FileName);
					var imagePath = Path.Combine(_environment.ContentRootPath,
					"wwwroot", uploadsFolder, imageFile);
					using var fileStream = new FileStream(imagePath,
					FileMode.Create);
					await Upload.CopyToAsync(fileStream);
					URL = string.Format("/{0}/{1}", uploadsFolder,
					imageFile);
				}

				var user = new ApplicationUser()
				{
					UserName = RModel.Email,
					Email = RModel.Email,
					FullName = RModel.FullName,
					Gender = RModel.Gender,
					ImageURL = URL
				};

				IdentityRole role = await roleManager.FindByIdAsync("Admin");
				if (role == null)
				{
					IdentityResult result2 = await roleManager.CreateAsync(new IdentityRole("Admin"));
					if (!result2.Succeeded)
					{
						ModelState.AddModelError("", "Create role admin failed");
					}
				}

				IdentityRole role2 = await roleManager.FindByIdAsync("Admin");
				if (role2 == null)
				{
					IdentityResult result3 = await roleManager.CreateAsync(new IdentityRole("User"));
					if (!result3.Succeeded)
					{
						ModelState.AddModelError("", "Create role user failed");
					}
				}

				var result = await userManager.CreateAsync(user, RModel.Password);
				if (result.Succeeded)
				{
					result = await userManager.AddToRoleAsync(user, "User");
					await signInManager.SignInAsync(user, false);
					var context = MyDbContext;
					var info = new Analytics { };
					var loginlist = new loginlist { };
					var list = context.Analytics.ToList();
					//add information   
					info.ApplicationUser = user;
					info.LoginCount++;

					loginlist.ApplicationUser = user;
					context.Analytics.Add(info);
					context.loginlist.Add(loginlist);
					context.SaveChanges();


					result = await userManager.AddToRoleAsync(user, "User");
					result = await userManager.AddToRoleAsync(user, "Admin");
					await signInManager.SignInAsync(user, false);
					return Redirect("/");
				}
				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}
			}
			return Page();
		}
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/AdminUserlist.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
	[Authorize(Roles = "Admin")]
	public class AdminUserlistModel : PageModel
	{

		[BindProperty]
		public List<ApplicationUser>? Allusers { get; set; }
		private UserManager<ApplicationUser> userManager { get; }

		private SignInManager<ApplicationUser> signInManager { get; }

		public AdminUserlistModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
		}
		public void OnGet()
		{
			Allusers = userManager.Users.ToList();
		}
		public async Task<IActionResult> OnPostDeleteAccAsync(string id)
		{
			var user = userManager.FindByIdAsync(id).Result;
			user.Deleted = true;
			var result = await userManager.UpdateAsync(user);
			if (result.Succeeded)
			{
				return Redirect("/usermanagement/AdminUserlist");
			}
			return Redirect("/");
		}
		public async Task<IActionResult> OnPostUnDeleteAccAsync(string id)
		{
			var user = userManager.FindByIdAsync(id).Result;
			user.Deleted = false;
			var result = await userManager.UpdateAsync(user);
			if (result.Succeeded)
			{
				return Redirect("/usermanagement/AdminUserlist");
			}
			return Redirect("/");
		}
		public async Task<IActionResult> OnPostSuspendAsync(string id)
		{
			var user = userManager.FindByIdAsync(id).Result;
			user.Suspended = true;
			var result = await userManager.UpdateAsync(user);
			if (result.Succeeded)
			{
				return Redirect("/usermanagement/AdminUserlist");
			}
			return Redirect("/");
		}
		public async Task<IActionResult> OnPostUnsuspendAsync(string id)
		{
			var user = userManager.FindByIdAsync(id).Result;
			user.Suspended = false;
			var result = await userManager.UpdateAsync(user);
			if (result.Succeeded)
			{
				return Redirect("/usermanagement/AdminUserlist");
			}
			return Redirect("/");
		}
		public void OnPostUpdateAcc(string id)
		{
			Response.Redirect($"/usermanagement/Update?Id={id}");
		}

		//add new page to change password using admin
		public void OnPostChangePassword(String id)
		{
			Response.Redirect($"/usermanagement/Changepassword?ID={id}");
		}

	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Changepassword.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement

{
	public class ChangepasswordModel : PageModel
	{


		[BindProperty]
		public ChangePassword Changepassword { get; set; } = new ChangePassword();
		public string? email { get; set; }
		public string? username { get; set; }

		private UserManager<ApplicationUser> userManager { get; }

		private SignInManager<ApplicationUser> signInManager { get; }

		public ChangepasswordModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
		}
		public void OnGet()
		{
			
			string page = HttpContext.Request.Query["Id"].ToString();
			if (page == string.Empty)
			{
				var user = userManager.FindByNameAsync(User?.Identity?.Name).Result;
				email = user.Email;
				username = user.UserName;
			}
			else
			{
				var pageresult = userManager.FindByIdAsync(page).Result;
				email = pageresult.Email;
				username = pageresult.UserName;
			}

		}
		public async Task<IActionResult> OnPostAsync()
		{

			if (ModelState.IsValid)
			{
				
				var user = new ApplicationUser();
				string page = HttpContext.Request.Query["Id"].ToString();
				if (page == string.Empty)
				{
					try
					{
						var object1 = userManager.FindByNameAsync(User?.Identity?.Name).Result;
						page = object1.Id;
						user = userManager.FindByIdAsync(page).Result;
					}
					catch
					{
						return Redirect("/");
					}

				}
				else
				{
					user = await userManager.FindByIdAsync(page);
				}

				var token = await userManager.GeneratePasswordResetTokenAsync(user);

				var result = await userManager.ResetPasswordAsync(user, token, Changepassword.newpassword);


				if (result.Succeeded)
				{
					return Redirect("/");
				}

				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}
			}
			return Page();
		}

	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Changepassworduser.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
	[Authorize]
    public class ChangepassworduserModel : PageModel
    {
		[BindProperty]
		public Changepassworduser Changepassworduser { get; set; } = new Changepassworduser();
		public string? email { get; set; }
		public string? username { get; set; }

		private UserManager<ApplicationUser> userManager { get; }

		private SignInManager<ApplicationUser> signInManager { get; }

		public ChangepassworduserModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
		}
		public void OnGet()
		{

			string page = HttpContext.Request.Query["Id"].ToString();
			if (page == string.Empty)
			{
				var user = userManager.FindByNameAsync(User?.Identity?.Name).Result;
				email = user.Email;
				username = user.UserName;
			}
			else
			{
				var pageresult = userManager.FindByIdAsync(page).Result;
				email = pageresult.Email;
				username = pageresult.UserName;
			}

		}
		public async Task<IActionResult> OnPostAsync()
		{

			if (ModelState.IsValid)
			{

				var user = new ApplicationUser();
				string page = HttpContext.Request.Query["Id"].ToString();
				if (page == string.Empty)
				{
					try
					{
						var object1 = userManager.FindByNameAsync(User?.Identity?.Name).Result;
						page = object1.Id;
						user = userManager.FindByIdAsync(page).Result;
					}
					catch
					{
						return Redirect("/");
					}

				}
				else
				{
					user = await userManager.FindByIdAsync(page);
				}

				var token = await userManager.GeneratePasswordResetTokenAsync(user);

				var result = await userManager.ChangePasswordAsync(user, Changepassworduser.oldpassword,Changepassworduser.newpassword);


				if (result.Succeeded)
				{
					return Redirect("/");
				}

				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}
			}
			return Page();
		}
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
	public class LoginModel : PageModel
	{
		[BindProperty]
		public Login LModel { get; set; } = new();


		private UserManager<ApplicationUser> UserManager;
		private MyDbContext MyDbContext;

		private readonly SignInManager<ApplicationUser> signInManager;
		public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, MyDbContext myDbContext)

		{
			this.signInManager = signInManager;
			this.UserManager = userManager;
			this.MyDbContext = myDbContext;
		}
		public void OnGet()
		{
		}
		public async Task<IActionResult> OnPostAsync()
		{
			if (1 == 1)
			{
				var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
				LModel.RememberMe, false);
				var info = new Analytics { };
				var context = MyDbContext;

				var list = context.Analytics.ToList();

				if (identityResult.Succeeded)
				{
					var result = await UserManager.FindByEmailAsync(LModel.Email);


					if (result.Suspended || result.Deleted == true)
					{
						ModelState.AddModelError(string.Empty, "Account Suspended/Deleted please contact admin");
						await signInManager.SignOutAsync();
						return Page();
					}

					var trackingdata = new loginlist { };
					trackingdata.ApplicationUser = UserManager.FindByNameAsync(LModel.Email).Result;
					context.loginlist.Add(trackingdata);

					if (list.IsNullOrEmpty())
					{
						info.ApplicationUser = result;
						info.LoginCount++;
						context.Analytics.Add(info);
						context.SaveChanges();
					}
					else
					{
						foreach (var item in list)
						{
							if (item.ApplicationUser?.Id == result.Id)
							{
								var analytic = context.Analytics.First(b => b.ApplicationUser.Email == LModel.Email);
								analytic.LoginCount++;

								context.SaveChanges();
								break;
							}
							else
							{
								info.ApplicationUser = result;
								info.LoginCount++;
								context.Analytics.Add(info);
								context.SaveChanges();
							}
						}
					}
					return Redirect("/");
				}
				foreach (var item in list)
				{
					if (item.ApplicationUser?.Email == LModel.Email)
					{
						using (var data = context)
						{
							var analytic = context.Analytics
								.Single(b => b.ApplicationUser.Email == LModel.Email);
							analytic.FailedLogin++;

							context.SaveChanges();
						}

					}
				}

				ModelState.AddModelError(string.Empty, "Username or Password incorrect");


			}
			return Page();
		}
		public IActionResult OnForgotPass(string id)
		{
			return RedirectToPage("forgetpass");
		}
	}
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SusFoodBank.Models;

namespace SusFoodBank.Pages.UserManagement
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet() { }
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
    }
}

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/AccountDetails.cshtml
@page
@using Microsoft.AspNetCore.Identity;
@using SusFoodBank.Models;
@model SusFoodBank.Pages.UserManagement.AccountDetailsModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    var usr = await UserManager.GetUserAsync(User);
    var email = usr?.Email;
    var sus = "";
    if (usr.Suspended == true)
    {
        sus = "Suspended";
    }
    else
    {
        sus = "normal";
    }
}
<div class="container my-4">
    

        <div class="row">
            <div class="col">
                <div class="card py-3 mx-auto ">
                <div class="card-body text-center">
                    <div class="row"></div>
                    <img class="rounded-circle" src=@usr?.ImageURL style="width:200px; height:200px" />
                <div>
                        <a asp-page="/UserManagement/Changepassworduser" class="btn btn-primary">
                        
                        <i class="solid me-1"></i>Update password
                    </a>
            </div>
            <div >
                        <a asp-page="/UserManagement/Update" class="btn btn-primary">
                        <i class=" solid me-1"></i>Update Particulars
                    </a>
            </div>
                <div>
                    <form asp-page-handler="DeleteAcc" method="post">
                        <button class="btn btn-primary solid me-1">Delete account(debug)</button>
                    </form>
                </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card py-3 mx-auto" style="max-width: 1000px;">
                    <div class="card-body">
                    <h3 class="fw-bold text-center mb-3">Account Details</h3>
                        <hr />
                        <br />
                    <div class="text-center">
                        <p>Username: @usr?.FullName</p>
                        <p>Email: @usr?.Email</p>
                        <p>Gender: @usr?.Gender</p>
                        <p>Status: @sus</p>
                </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="row">
        <div class=" py-3 mx-auto" style="max-width: 1000px;">
            <h1 class="fw-bold text-center mb-3">Statistics</h1>
            </div>
    </div>
        <div class="row">
            <div class="col">
                <div class="card py-3 mx-auto" style="">
                <div>
                    <canvas id="myChart"></canvas>
                </div>
                </div>
            </div>
        <div class="col">
            <div class="card py-3 mx-auto" style="">
                <div>
                    <canvas id="totallogin"></canvas>
                </div>
            </div>
        </div>
        </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: @Html.Raw(Model.datelist),
      datasets: [{
        label: 'No of times logged in',
        data: @Html.Raw(Model.datevalue),
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true,
              suggestedMin: 50,
                    suggestedMax: 100
        }
      }
    }
  });
</script>

<script>
  const totallogin = document.getElementById('totallogin');

  new Chart(totallogin, {
    type: 'bar',
    data: {
      labels: ["Total times logged in"],
      datasets: [{
        label: 'No of times logged in',
        data: [@Model.NoLogin],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true,
              suggestedMin: 5,
                    suggestedMax: 10
        }
      }
    }
  });
</script>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/AdminUserlist.cshtml
@page
@model SusFoodBank.Pages.UserManagement.AdminUserlistModel
@{
	
}

<div class="container py-5 table table-responsive " style="overflow-x:auto;">
	<h1>List Of Users </h1>
	<div class="table table-dark overflow-auto" style="overflow-x:auto;">
		<table class="table table-striped table-hover overflow-auto ">
            <thead>
                <tr>
                    <th scope="col" >id</th>
					<th scope="col" style="width:300px">Fullname</th>
                    <th scope="col" >Gender</th>
					<th scope="col" style="width:300px">email</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model.Allusers){
                <tr>
						<th scope="row"> <div class="text-overflow">@i.Id</div></th>
                    <td>@i.FullName</td>
                    <td>@i.Gender</td>
						<td ><div class="text-overflow">@i.Email</div></td>
					<td>
							<form asp-page-handler="UpdateAcc" method="post" class="align-self-center">
								<input type="hidden" hidden="hidden" value="@i.Id" name="id">
								<button class="btn btn-primary">Update</button>
						</form>
					</td>
					<td>
						@if (i.Deleted != true){
							<form asp-page-handler="DeleteAcc" method="post" class="align-self-center">
							<input type="hidden"  hidden="hidden" value="@i.Id" name="id">
								<button class="btn btn-danger">Delete</button>
							</form>
						}
						else {

								<form asp-page-handler="UnDeleteAcc" method="post" class="align-self-center">
									<input type="hidden" hidden="hidden" value="@i.Id" name="id">
									<button class="btn btn-danger">UnDelete</button>
								</form>
							
						}
					</td>
					<td>
							<form asp-page-handler="ChangePassword" method="post" class="align-self-center">
							<input type="hidden" hidden="hidden" value="@i.Id" name="id">
								<button class="btn btn-primary">Change Password</button>
						</form>
					</td>
					<td>
							@if (i.Suspended == true)
							{
								<form asp-page-handler="Unsuspend" method="post" class="align-self-center">
							<input type="hidden" hidden="hidden" value="@i.Id" name="id">
									<button class="btn btn-primary">Unsuspend</button>
								</form>
							}
							else
							{
								<form asp-page-handler="Suspend" method="post" class="align-self-center">
							<input type="hidden" hidden="hidden" value="@i.Id" name="id">
									<button class="btn btn-danger">suspend</button>
								</form>
							}
					</td>
                </tr>

                }
            </tbody>
        </table>

	</div>

</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Changepassword.cshtml
@page
@model SusFoodBank.Pages.UserManagement.ChangepasswordModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Update </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

@*				<div class="mb-3">
					<label class="form-label" asp-for="Changepassword.oldpassword">Old Password</label>
					<input type="Text" asp-for="Changepassword.oldpassword" class="form-control"  />
					<span asp-validaton-for="Changepassword.oldpassword" class="text-danger"></span>
				</div>*@

				<div class="mb-3">
					<label class="form-label" asp-for="Changepassword.newpassword">New password</label>
					<input type="Text" asp-for="Changepassword.newpassword" class="form-control" />
					<span asp-validaton-for="Changepassword.newpassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Update</button>
				</div>

			</form>


		</div>
	</div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Changepassworduser.cshtml
@page
@model SusFoodBank.Pages.UserManagement.ChangepassworduserModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Update </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="Changepassworduser.oldpassword">Old Password</label>
					<input type="Text" asp-for="Changepassworduser.oldpassword" class="form-control"  />
					<span asp-validaton-for="Changepassword.oldpassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="Changepassworduser.newpassword">New password</label>
					<input type="Text" asp-for="Changepassworduser.newpassword" class="form-control" />
					<span asp-validaton-for="Changepassword.newpassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Update</button>
				</div>

			</form>


		</div>
	</div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/Logout.cshtml
@page
@model SusFoodBank.Pages.UserManagement.LogoutModel
@{
    ViewData["Title"] = "Logout Confirmation";
}

<div class="my-4">
    <div class="card mx-auto" style="max-width: 450px;">
        <div class="card-body my-3">
            <div class="mb-5">
                <h3 class="fw-bold mb-4">Logout Confirmation</h3>
                <p>You are about to be logged out.</p>
                <p>Please note that your current session will end if you proceed. You will need to re-enter your credentials the next time you visit this website.</p>
                <small class="fw-bold text-danger">
                    <i class="fa-solid fa-user-secret me-1"></i>To better protect your account, please clear your browser cache and cookies if you are on a public computer.
                </small>
            </div>
            <form method="post">
                <div class="d-flex flex-row-reverse">
                    <button class="btn btn-primary" asp-page-handler="Logout">Logout</button>
                    <button class="btn btn-link" onclick="javascript:window.history.back(-1);return false;">No, take me back!</button>
                </div>
            </form>
        </div>
    </div>
</div>

SusFoodBank (ASP.NET Core)/SusFoodBank/Pages/UserManagement/forgetpass.cshtml
@page
@model SusFoodBank.Pages.UserManagement.forgetpassModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Forget Password</h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="@Model.Email">Email Address</label>
					<input type="Text" asp-for=@Model.Email class="form-control" />
					<span asp-validaton-for="@Model.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Update</button>
				</div>

			</form>


		</div>
	</div>
</div>